import {Game} from './app/shared/models/game';

export const list_games: Game[] = [
    { gameid: 1,
        gamename:  'adasddasd',
        price: 0,
        describtion:'',
        dev:'',
        img_logo: 'assets/images/dota2logo.jpg',
        img_banner: 'assets/images/dota2banner.jpg',
        img_ss1: '',
        img_ss2: '',
        img_ss3: '',
        },
    { gameid: 2,
        gamename:  'Dota2',
        price: 0,
        describtion:'',
        dev:'',
        img_logo: 'assets/images/dota2logo.jpg',
        img_banner: 'assets/images/dota2banner.jpg',
        img_ss1: '',
        img_ss2: '',
        img_ss3: '',
        },
        { gameid: 3,
            gamename:  'Dota3',
            price: 0,
            describtion:'',
            dev:'',
            img_logo: 'assets/images/dota2logo.jpg',
            img_banner: 'assets/images/dota2banner.jpg',
            img_ss1: '',
            img_ss2: '',
            img_ss3: '',
            },
            { gameid: 4,
                gamename:  'Dota4',
                price: 0,
                describtion:'',
                dev:'',
                img_logo: 'assets/images/dota2logo.jpg',
                img_banner: 'assets/images/dota2banner.jpg',
                img_ss1: '',
                img_ss2: '',
                img_ss3: '',
                }
]